function(configure_vcpkg_features)
    if(BUILD_TESTING)
        list(APPEND VCPKG_MANIFEST_FEATURES "testing")
    endif()

    if(BUILD_RUNTIME)
        list(APPEND VCPKG_MANIFEST_FEATURES "runtime")
    endif()

    if(BUILD_EXAMPLE)
        list(APPEND VCPKG_MANIFEST_FEATURES "example")
    endif()

    set(VCPKG_MANIFEST_FEATURES "${VCPKG_MANIFEST_FEATURES}" PARENT_SCOPE)
endfunction()

function(configure_packages)
    if(BUILD_TESTING)
        find_package(maxtest CONFIG REQUIRED)
    endif()
    if(BUILD_RUNTIME)
        find_package(Libevent CONFIG REQUIRED)
        if(NOT WIN32)
            find_package(cef CONFIG REQUIRED)
        endif()
        find_package(wxWidgets CONFIG REQUIRED)
    endif()
    if(BUILD_EXAMPLE)
        find_package(unofficial-sqlite3 REQUIRED)
        find_package(yyjson CONFIG REQUIRED)
        find_package(megamimes CONFIG REQUIRED)
        find_package(hyperpage CONFIG REQUIRED)
    endif()
endfunction()