name: WebFrame CI/CD Pipeline

on:
  push:

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      VCPKG_BINARY_SOURCES: >-
        clear;files,${{ github.workspace }}/vcpkg-test-cache,readwrite
    steps:
    - name: Checkout vcpkg
      uses: actions/checkout@v6
      with:
        repository: microsoft/vcpkg
        path: vcpkg
        ref: '2026.01.16'  

    - name: Checkout code
      uses: actions/checkout@v6
      with:
        repository: maxtek6/WebFrame
        path: WebFrame
        ref: ${{ github.ref }}

    - name: "Restore VCPKG cache"
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/vcpkg-test-cache
        key: vcpkg-test-cache
        restore-keys: vcpkg-test-cache

    - name: CMake Build
      run: |
        cmake -S WebFrame -B build -DBUILD_TESTING=ON -DBUILD_RUNTIME=OFF -DVCPKG_ROOT=${{ github.workspace }}/vcpkg
        cmake --build build

    - name: "Save VCPKG cache"
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/vcpkg-test-cache
        key: vcpkg-test-cache

  build:
    needs: test
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]
    env: 
      VCPKG_BINARY_SOURCES: >-
        clear;files,${{ github.workspace }}/vcpkg-${{ matrix.os }},readwrite
    steps:
    - name: Checkout vcpkg
      uses: actions/checkout@v6
      with:
        repository: microsoft/vcpkg
        path: vcpkg
        ref: '2026.01.16'  

    - name: Checkout code
      uses: actions/checkout@v6
      with:
        repository: maxtek6/WebFrame
        path: WebFrame
        ref: ${{ github.ref }}

    - name: "Restore VCPKG cache"
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/vcpkg-${{ matrix.os }}
        key: vcpkg-${{ matrix.os }}
        restore-keys: vcpkg-${{ matrix.os }}

    - name: Ubuntu setup
      if: matrix.os == 'ubuntu-latest'
      run: ./WebFrame/.github/scripts/ubuntu_setup.sh

    - name: MacOS setup
      if: matrix.os == 'macos-latest'
      run: ./WebFrame/.github/scripts/osx_setup.sh

    - name: CMake Build
      run: |
        cmake -S WebFrame -B build -DBUILD_TESTING=OFF -DBUILD_RUNTIME=ON -DVCPKG_ROOT=${{ github.workspace }}/vcpkg
        cmake --build build

    - name: "Save VCPKG cache"
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/vcpkg-${{ matrix.os }}
        key: vcpkg-${{ matrix.os }}